force-app/main/default/objects/Case/fields/Customer_Services_Comments__c.field-meta.xml
<CustomField>
    <fullName>Customer_Services_Comments__c</fullName>
    <inlineHelpText>Enter any internal comments</inlineHelpText>
    <label>Customer Services Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <label>Service Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult Social Care</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Blue Badges</fullName>
            </value>
            <value>
                <fullName>Children Social Care</fullName>
            </value>
            <value>
                <fullName>Council Tax</fullName>
            </value>
            <value>
                <fullName>Democratic services</fullName>
            </value>
            <value>
                <fullName>Elections</fullName>
            </value>
            <value>
                <fullName>Environmental issues</fullName>
            </value>
            <value>
                <fullName>Highways</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Registrars</fullName>
            </value>
            <value>
                <fullName>School Admissions</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Waste</fullName>
            </value>
            <value>
                <fullName>Street Scene</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Area_Detail__c.field-meta.xml
<CustomField>
    <fullName>Service_Area_Detail__c</fullName>
    <label>Service Area - Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Service_Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missed Bin</fullName>
            </value>
            <value>
                <fullName>Damaged Bin</fullName>
            </value>
            <value>
                <fullName>Replacement Bin</fullName>
            </value>
            <value>
                <fullName>Remove Bin</fullName>
            </value>
            <value>
                <fullName>Additional Bin</fullName>
            </value>
            <value>
                <fullName>New Property Bin</fullName>
            </value>
            <value>
                <fullName>Communal Bin Issue</fullName>
            </value>
            <value>
                <fullName>Apply for Assisted Collection</fullName>
            </value>
            <value>
                <fullName>Bulky Collection</fullName>
            </value>
            <value>
                <fullName>General Waste</fullName>
            </value>
            <value>
                <fullName>Street Cleansing</fullName>
            </value>
            <value>
                <fullName>Abandoned Vehicles</fullName>
            </value>
            <value>
                <fullName>Discarded Syringes</fullName>
            </value>
            <value>
                <fullName>Trees or Vegetation</fullName>
            </value>
            <value>
                <fullName>Dead Animal</fullName>
            </value>
            <value>
                <fullName>Missed Grass Cutting</fullName>
            </value>
            <value>
                <fullName>Graffiti</fullName>
            </value>
            <value>
                <fullName>Fly Tipping</fullName>
            </value>
            <value>
                <fullName>Fly Posting</fullName>
            </value>
            <value>
                <fullName>Change of Circs</fullName>
            </value>
            <value>
                <fullName>Kerbs</fullName>
            </value>
            <value>
                <fullName>Traffic Signals</fullName>
            </value>
            <value>
                <fullName>Rights of Way</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Street Lighting</fullName>
            </value>
            <value>
                <fullName>Street Name Plate</fullName>
            </value>
            <value>
                <fullName>Street Furniture</fullName>
            </value>
            <value>
                <fullName>Retaining Wall</fullName>
            </value>
            <value>
                <fullName>Road Signage</fullName>
            </value>
            <value>
                <fullName>Footway or Footpath</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FixMyStreet.recordType-meta.xml
<RecordType>
    <fullName>FixMyStreet</fullName>
    <active>true</active>
    <businessProcess>FixMyStreetProcess</businessProcess>
    <description>FixMyStreet Records</description>
    <label>FixMyStreet</label>
</RecordType>

force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/ConfirmReference__c.field-meta.xml
<CustomField>
    <fullName>ConfirmReference__c</fullName>
    <label>ConfirmReference</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Easting__c.field-meta.xml
<CustomField>
    <fullName>Easting__c</fullName>
    <label>Easting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Extends_Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Extends_Additional_Information__c</fullName>
    <label>Additional Information</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/lat__c.field-meta.xml
<CustomField>
    <fullName>lat__c</fullName>
    <description>Latitude</description>
    <label>lat</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>CST Described Location</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/long__c.field-meta.xml
<CustomField>
    <fullName>long__c</fullName>
    <description>Longitude</description>
    <label>long</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Northing__c.field-meta.xml
<CustomField>
    <fullName>Northing__c</fullName>
    <label>Northing</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/requested_datetime__c.field-meta.xml
<CustomField>
    <fullName>requested_datetime__c</fullName>
    <label>Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Area</label>
    <referenceTo>FixMyStreetCategories__c</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/service_request_id__c.field-meta.xml
<CustomField>
    <fullName>service_request_id__c</fullName>
    <label>Service request id</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/SiteCode__c.field-meta.xml
<CustomField>
    <fullName>SiteCode__c</fullName>
    <label>SiteCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Log__c/FixMyStreet_Log__c.object-meta.xml
<CustomObject>
    <label>FixMyStreet Log</label>
    <nameField>
        <displayFormat>FMSLog-{00000}</displayFormat>
        <label>FixMyStreet Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet_Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/FixMyStreetCategories__c.object-meta.xml
<CustomObject>
    <description>A holding table of FixMyStreet Categories</description>
    <label>FixMyStreetCategories</label>
    <nameField>
        <label>FixMyStreetCategories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FixMyStreetCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreetCategories__c/fields/InternalQueue__c.field-meta.xml
<CustomField>
    <fullName>InternalQueue__c</fullName>
    <label>InternalQueue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Send_to_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Confirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Confirm</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <label>Service Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreetSendCategories__mdt/FixMyStreetSendCategories__mdt.object-meta.xml
<CustomObject>
    <label>FixMyStreetSendCategories</label>
    <pluralLabel>FixMyStreetSendCategories</pluralLabel>
</CustomObject>

force-app/main/default/objects/FixMyStreetSendCategories__mdt/fields/InternalQueue__c.field-meta.xml
<CustomField>
    <fullName>InternalQueue__c</fullName>
    <label>InternalQueue</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreetSendCategories__mdt/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FixMyStreetSendCategories__mdt/fields/Send_To_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Send_To_Confirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send To Confirm</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FixMyStreetSendCategories__mdt/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <label>Service Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FixMyStreetCreateCase.cls
global with sharing class FixMyStreetCreateCase {

      
    public class Child {
    public String name;
    public String label;
    public String fieldType;
    public String length;
    public String[] optionsList = new String[] {};
	}
    
    
    public static Child[] GetFixMyStreetExtends(string FixMyStreetId) {
       
        Child[] resultList = new Child[] {};
        
       Child cAddInfoTitle = new Child();
       cAddInfoTitle.name = 'title__c';
       cAddInfoTitle.label = 'Short Summary of Problem';
       cAddInfoTitle.fieldType = 'text';
       cAddInfoTitle.length = '1000';
       resultList.add(cAddInfoTitle);

        // always in the basics
       Child cAddInfoDesc = new Child();
       cAddInfoDesc.name = 'Description__c';
       cAddInfoDesc.label = 'Description of problem';
       cAddInfoDesc.fieldType = 'text';
       cAddInfoDesc.length = '1000';
       resultList.add(cAddInfoDesc);
       
        
        
        
        
        // need to look up friendly description of code from id
        FixMyStreetSendCategories__mdt res_category =  database.query('SELECT service_code__c FROM FixMyStreetSendCategories__mdt where Live__C=true and Id=:FixMyStreetId');
        string servicecategory = res_category.service_code__c;
            
        Map<String, Schema.SObjectField> fieldsResult = Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().fields.getMap();
        //get object fields
        List<String> fieldList = new List<String>(Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().fields.getMap().keySet());
        String fields = String.join(fieldList,',');       
            
            for (String fieldName: fieldsResult.keySet()) {
               if (fieldName.startsWithIgnoreCase('Extends_'+servicecategory))
                {
                 Child c = new Child();
        		 c.name = fieldname;
        		 c.label = fieldsResult.get(fieldname).getDescribe().getLabel();
                 Schema.DisplayType fielddataType = fieldsResult.get(fieldname).getDescribe().getType();
                    if (fielddataType == Schema.DisplayType.String) {
				   	 	c.fieldType = 'text';
                        Integer length = fieldsResult.get(fieldname).getDescribe().getLength();
                        c.length = String.valueOf(length);
                    } else if (fielddataType == Schema.DisplayType.TextArea) {
				   	 	c.fieldType = 'text';
                        Integer length = fieldsResult.get(fieldname).getDescribe().getLength();
                        c.length = String.valueOf(length);
                    } else if (fielddataType == Schema.DisplayType.Picklist) {
				   	 	c.fieldType = 'options';
                        List<Schema.PicklistEntry>Picks =fieldsResult.get(fieldname).getDescribe().getpicklistValues();
                        for (Schema.PicklistEntry pick: Picks) {
                        c.optionsList.add(pick.getValue());
                        }
                    } 
        		 resultList.add(c);
                }    
    		}
       // always add in additional information
       Child cAddInfoAdd = new Child();
       cAddInfoAdd.name = 'extends_additional_information__c';
       cAddInfoAdd.label = 'Additional Information';
       cAddInfoAdd.fieldType = 'text';
       cAddInfoAdd.length = '1000';
       resultList.add(cAddInfoAdd);

        
        //string result  = JSON.serializePretty(resultList); 
        //return result;
        return resultList;
       }

    
	@InvocableMethod
    public static void doCreationCase(List<FMSRequests> requests) {

        
        if (requests == null)
       {
           system.debug('No id sent to doCreationCase');
           return;
       }

        FMSRequests firstRequest = requests[0];
        
       Id fixmystreetId = firstRequest.fixmystreetId;
       boolean force = firstRequest.force;
       system.debug('doCreationCase '+ fixmystreetId);
        NewCaseFromFixMyStreetId(fixmystreetId,force);
    }

    
    global  class FMSRequests {
        @InvocableVariable
        global Id fixmystreetId;
        @InvocableVariable
        global boolean force = false;
    }

    public static void ConfirmLogEntry(string log) {
        // send the result to the log object
        FixMyStreet_Log__c logEntry = new FixMyStreet_Log__c();
        logEntry.Log__c = log;
        insert logEntry;
    }
    
    @future (callout=true)
    public static void NewCaseFromFixMyStreetId(Id fixmystreetId, boolean force) {


        system.debug(fixmystreetId);

        // force set to true
        // if we need to create case and remove confirm reference

        Boolean logError = false;
        string logEntry = 'NewCaseFromFixMyStreetId\r\n';
        
		FixMyStreet__c fixmystreet;
        fixmystreet = [SELECT id, Name, Service_Area__c,Service_Area__r.Name,title__c,Description__c,Easting__c, Northing__c,
                        requested_datetime__c,Contact_Name__c,Contact_Phone__c,Contact_Email__c,service_request_id__c,
                       lat__c, long__c,
                        Location__c, SiteCode__c,
                       ConfirmReference__c
                        FROM FixMyStreet__c 
                        WHERE FixMyStreet__c.id = :fixmystreetId
                        LIMIT 1
                       ];

        system.debug(fixmystreet);
        
        
        
        Id cat = fixmystreet.Service_Area__c;
        string ServiceArea = fixmystreet.Service_Area__r.Name;
        system.debug(ServiceArea);
        system.debug(cat);

        // check if we should integrate to Confirm and therefore not setup a case
        FixMyStreetCategories__c categoryCheck;
        categoryCheck = [SELECT Send_to_Confirm__c, InternalQueue__c FROM FixMyStreetCategories__c where Id=: cat LIMIT 1];
       // sendEmailMessage('SALESFORCE - Debug New Confirm Entry - 2', '2', 'anix@rutland.gov.uk');
        
        if (categoryCheck!=null && !force)
        {
            if (categoryCheck.Send_to_Confirm__c == true)
            {
                // in wrong place return 
       			 system.debug('---This category integrates to Confirm so case creation not allowed---');
                return;
            }
        }
        
        
	      //  need a list of all the extend fields in the record
    	Child[] resultList = GetFixMyStreetExtends(cat); 
   		System.debug(resultList);

        string soql = 'SELECT ';
        for (Child indList : resultList)
                {
                    //system.debug(indList.Name);
                    soql = soql + indList.Name + ', ';
                }
        soql = soql + 'Name FROM FixMyStreet__c WHERE FixMyStreet__c.id = \''+fixmystreetId+ '\' LIMIT 1';
		system.debug(soql);
        
		FixMyStreet__c fixmystreetExtend;
        fixmystreetExtend = Database.query(soql);
        system.debug('====Extends====');
        system.debug(fixmystreetExtend);
        
        // We have a the Id of the Service Area
        
       
        
        string fullDescription = '';
        string newline = '\r\n';
        if (fixmystreet.title__c != null)
            {
            fullDescription = fullDescription + 'Summary: '+fixmystreet.title__c+newline;
            }
        if (fixmystreet.Description__c != null)
            {
	        fullDescription = fullDescription + 'Description: '+fixmystreet.Description__c+newline;
            }
        
        for (Child indList : resultList)
                {
                    Object fieldval = fixmystreetExtend.get(indList.Name);
                    system.debug('=====');
                    system.debug(fieldval);
                    if (indList.Name != 'title__c'  && indList.Name != 'Description__c' && fieldval != null)
                    {
                        if (fieldval.ToString() != '')
                        {
                        fullDescription = fullDescription + indList.label + ': '+fieldval.ToString()+newline;
                        }
                    }
                }
        system.debug(fullDescription); 


    
        
        Datetime dateEnquiryLogtime;
        if (fixmystreet.requested_datetime__c != null)
        {
            dateEnquiryLogtime = fixmystreet.requested_datetime__c;
        }
        else
        {
            dateEnquiryLogtime = DateTime.now();
        }
        
        
        
        string enquiryLogTime = dateEnquiryLogtime.format('yyyy-MM-dd\'T\'HH:mm');
        string CSTlocation = '';
        if (fixmystreet.Location__c != null)
        {
            CSTlocation = fixmystreet.Location__c;
        }
        string crmRef = fixmystreet.Name;
        string custSurname = 'Not Known';
        if (fixmystreet.Contact_Name__c != null)
        {
            custSurname = fixmystreet.Contact_Name__c;
        }
        string custPhone = '';
        if (fixmystreet.Contact_Phone__c != null)
        {
            custPhone = fixmystreet.Contact_Phone__c;
        }
        string custEmail = '';
        if (fixmystreet.Contact_Email__c != null)
        {
            custEmail = fixmystreet.Contact_Email__c;
        }
        
        

        system.debug('---ready to create case----');
        
        
        string orgId = UserInfo.getOrganizationId();
        system.debug('OrgId: '+orgId);
        boolean production = false;
        if (orgId == '00D0Y000002EzYY')
        {
            production = true;
        }
        
        
            
        
        
        string body = '';
        if (fixmystreet.service_request_id__c>0)
        {
            body = body + 'Recorded via the National FixMyStreet Service'+newline;
        }
        else
        {
            body = body + 'Recorded via Customer Services Team'+newline;
        }
        
        
        body = body + fullDescription+newline;
        if (CSTLocation != '')
        {
	        body = body + 'CST Described Location: '+CSTLocation+newline;        
        }
        body = body + 'Name: '+custSurname+newline;        
        body = body + 'Phone: '+custPhone+newline;
        body = body + 'Email: '+custEmail+newline;
        body = body + 'Area: '+ServiceArea +newline;
        
        System.debug(body);
       logEntry = logEntry + body+newline;                
       
        // was manually entered         '00G6E000003jeo1';
        // 
        Id caseRecordTypeId = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('FixMyStreet').getRecordTypeId();
        //Id ownerId = Schema.getGlobalDescribe().getSObjectType().getDescribe().getRecordTypeInfosByName().get('Internal Street Scene Waste Queue').getRecordTypeId();

        //newCase.OwnerId = '00G6E000003jeo1';
        string owner = categoryCheck.InternalQueue__c;
        system.debug(owner);
		//List<queueSobject> queues = [select queue.id from queueSobject where queue.Name = 'Internal Street Scene Waste Queue'];
        
		List<queueSobject> queues = [select queue.id from queueSobject where queue.Name =: owner];
        
        Id ownerId = null;
        if (queues.size() >0)
        {
            ownerId = queues[0].queue.id;
        }
        else
        {
            // problem with no queue found
			queues = [select queue.id from queueSobject where queue.Name = 'CST Main Queue'];
            if (queues.size()>0)
        		{
            	ownerId = queues[0].queue.id;
        		}
        }
        system.debug(ownerId);
        
		Case newCase = new Case();
        if (ownerid!=null)
        {
        newCase.OwnerId = ownerId;
        }
        //newCase.OwnerId = '00G6E000003jeo1';
        newCase.RecordTypeId = caseRecordTypeId;
        newCase.Service_Area__c = 'Street Scene';
        // if we have force then may not be a street scene service area
        if (!force)
        {
        newCase.Service_Area_Detail__c = ServiceArea;
        }
        newCase.Subject = ServiceArea + ' - ' + fixmystreet.title__c;
        newCase.Customer_Services_Comments__c = CSTLocation;
        newCase.Description = body;

		
		insert newCase;                               
        
        //now link case and FxMyStreet record
     	fixmystreet.Case__c = newCase.Id;
        if (force)
        {
            // remove any confirm reference
            fixmystreet.ConfirmReference__c = null;
        }
        upsert fixmystreet;
        
       if (logError)
      {
          ConfirmLogEntry(logEntry);
      }
        
    }

    
}