force-app/main/default/objects/Case/fields/FixMyStreet_Public_Comment__c.field-meta.xml
<CustomField>
    <fullName>FixMyStreet_Public_Comment__c</fullName>
    <inlineHelpText>This test will be shown to the public when the case is closed.</inlineHelpText>
    <label>FixMyStreet Public Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FixMyStreet.recordType-meta.xml
<RecordType>
    <fullName>FixMyStreet</fullName>
    <active>true</active>
    <businessProcess>FixMyStreetProcess</businessProcess>
    <description>FixMyStreet Records</description>
    <label>FixMyStreet</label>
</RecordType>

force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/New_update_Comments__c.field-meta.xml
<CustomField>
    <fullName>New_update_Comments__c</fullName>
    <label>New update Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Investigating</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Action scheduled</fullName>
            </value>
            <value>
                <fullName>No further action</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not responsible</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Internal referral</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Update_FixMyStreet__c.field-meta.xml
<CustomField>
    <fullName>Update_FixMyStreet__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Setting this will ensure that changes to fields is sent to FixMyStreet</inlineHelpText>
    <label>Update FixMyStreet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FixMyStreetCreateCommentFromCase.cls
global with sharing class FixMyStreetCreateCommentFromCase {

	@InvocableMethod(label='FixMyStreet Create Comment from Case' description='Used to create a comment from the case FMS comments')
    public static void doComment(List<FMSRequests> requests) {

        
        if (requests == null)
       {
           system.debug('No id sent to doCreationConfirmRecord');
           return;
       }

        FMSRequests firstRequest = requests[0];
        
       Id CaseId = firstRequest.caseId;
        CreateComment(caseId);
    }

    
    global  class FMSRequests {

        @InvocableVariable
       global Id caseId;
    }

    public static void CreateComment(Id caseId) {

    // get case comment
    Case caseComment = [SELECT FixMyStreet_Public_Comment__c FROM Case where Id =: caseId LIMIT 1];

    // get the FixMyStreet info
    FixMyStreet__c fms = [SELECT Id,New_update_Comments__c,Name, Status__c from FixMyStreet__c WHERE Case__c=: caseId LIMIT 1];

    if (fms!=null)
    {   
        fms.New_update_Comments__c = caseComment.FixMyStreet_Public_Comment__c;
        fms.Status__c = 'Closed';
        fms.Update_FixMyStreet__c = true;
       upsert fms;
       // no remove comment on case
       caseComment.FixMyStreet_Public_Comment__c = '';
       upsert caseComment;
    }

    }
}