force-app/main/default/objects/Case/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <label>Service Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult Social Care</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Blue Badges</fullName>
            </value>
            <value>
                <fullName>Children Social Care</fullName>
            </value>
            <value>
                <fullName>Council Tax</fullName>
            </value>
            <value>
                <fullName>Democratic services</fullName>
            </value>
            <value>
                <fullName>Elections</fullName>
            </value>
            <value>
                <fullName>Environmental issues</fullName>
            </value>
            <value>
                <fullName>Highways</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Registrars</fullName>
            </value>
            <value>
                <fullName>School Admissions</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Waste</fullName>
            </value>
            <value>
                <fullName>Street Scene</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Area</label>
    <referenceTo>FixMyStreetCategories__c</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Investigating</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Action scheduled</fullName>
            </value>
            <value>
                <fullName>No further action</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not responsible</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Internal referral</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/recordTypes/RC11.recordType-meta.xml
<RecordType>
    <fullName>RC11</fullName>
    <active>true</active>
    <label>RC11</label>
</RecordType>

force-app/main/default/objects/FixMyStreetCategories__c/FixMyStreetCategories__c.object-meta.xml
<CustomObject>
    <description>A holding table of FixMyStreet Categories</description>
    <label>FixMyStreetCategories</label>
    <nameField>
        <label>FixMyStreetCategories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FixMyStreetCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <label>Service Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FixMyStreetController.cls
global with sharing class FixMyStreetController {
    
    public class PagedResult {
        
        @AuraEnabled
        public Integer pageSize { get;set; }
        
        @AuraEnabled
        public Integer page { get;set; }
        
        @AuraEnabled
        public Integer total { get;set; }
        
        @AuraEnabled
        public List<FixMyStreet__c> fixmystreets { get;set; }
        
    }


      @AuraEnabled
    public static PagedResult getResults(string status) {
        
    // each service category can use additonal fields to extend information
    // example  cateogy name abandoned Vehicles which is Service Code RC11 has fields in the main
    // Extends_RC11_xxxxx 
        
    Map<String, Schema.SObjectField> fieldsResult = Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().fields.getMap();
   //get object fields
    List<String> fieldList = new List<String>(Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().fields.getMap().keySet());
    String fields = String.join(fieldList,','); 
        
 
        

        Integer pSize = 0;
        PagedResult r =  new PagedResult();
        r.pageSize = pSize;
        r.page = 1;
        
        string soql = 'SELECT ' + fields + ',Service_Area__r.Name,Service_Area__r.Service_Code__c FROM FixMyStreet__c';
        if (status != 'All')
        	{
             soql = soql + ' where Status__c = : status';
        	}
        system.debug('####' + soql);
        system.debug('####' + status);
        r.fixmystreets = database.query(soql);
        
        return r;
    }

    @AuraEnabled
    public static PagedResult getFilteredResults(string status, string category) {
 
    // each service category can use additonal fields to extend information
    // example  cateogy name abandoned Vehicles which is Service Code RC11 has fields in the main
    // Extends_RC11_xxxxx 
        
    Map<String, Schema.SObjectField> fieldsResult = Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().fields.getMap();
   //get object fields
    List<String> fieldList = new List<String>(Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().fields.getMap().keySet());
    String fields = String.join(fieldList,','); 
        
        system.debug('#### status: ' + status);
        system.debug('#### category: ' + category);
       


        String strCategory;
        if (category == 'All')
        {
        	strCategory = 'All';
        }
        else
        {
        	strCategory = Id.valueOf(category);
        }
        
        system.debug('####' + strCategory);
        system.debug('####' + status);        
        
        Integer pSize = 0;
        PagedResult r =  new PagedResult();
        r.pageSize = pSize;
        r.page = 1;
    //    string soql = 'SELECT ' + fields + ',Service_Area__r.Name,Service_Area__r.Service_Code__c FROM FixMyStreet__c where Service_Area__c = :filter and Status__c = : status';
        string soql = 'SELECT ' + fields + ',Case__r.Status, Case__r.CaseNumber, Service_Area__r.Name,Service_Area__r.Service_Code__c FROM FixMyStreet__c';

        // ignoring status looking for open cases
        status = 'New';
        if (category != 'All')
        {
            soql = soql +  ' where Service_Area__c = :strCategory AND Case__r.Status=: status'; 
        } 
        else
        {
            soql = soql +  ' where Case__r.Status= :status'; 
        } 
            

            soql = soql +  ' ORDER BY CreatedDate DESC'; 
        
        
/*        if (status =='All')
        {
        	if (category != 'All')
        	{
         	soql = soql +  ' where Service_Area__c = :strCategory'; 
        	}        	
        }
        else
        {
        	if (category != 'All')
        	{
         	soql = soql +  ' where Service_Area__c = :strCategory and Status__c = : status'; 
        	}        	
        	else
        	{
         	soql = soql +  ' where Status__c = : status'; 
        	}        	
        }*/
        
        system.debug('####' + soql);

       
        
        r.fixmystreets = database.query(soql);
        
        return r;
    }    

    @AuraEnabled
    public static FixMyStreetCategories__c[] getCategories() {
        return [SELECT Id, Name FROM FixMyStreetCategories__c ORDER BY Name];
    }
    
    @AuraEnabled
    public static List<String> getStatus() {
 
        list<String> MyList = new list<String> ();
 
		Schema.DescribeFieldResult fieldResult = FixMyStreet__c.Status__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple)
   		{
            MyList.add(f.getLabel());
  		 }   
        
       
        return MyList;
    }
    
}