force-app/main/default/objects/Case/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <label>Service Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult Social Care</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Blue Badges</fullName>
            </value>
            <value>
                <fullName>Children Social Care</fullName>
            </value>
            <value>
                <fullName>Council Tax</fullName>
            </value>
            <value>
                <fullName>Democratic services</fullName>
            </value>
            <value>
                <fullName>Elections</fullName>
            </value>
            <value>
                <fullName>Environmental issues</fullName>
            </value>
            <value>
                <fullName>Highways</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Registrars</fullName>
            </value>
            <value>
                <fullName>School Admissions</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Waste</fullName>
            </value>
            <value>
                <fullName>Street Scene</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/ConfirmReference__c.field-meta.xml
<CustomField>
    <fullName>ConfirmReference__c</fullName>
    <label>ConfirmReference</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Easting__c.field-meta.xml
<CustomField>
    <fullName>Easting__c</fullName>
    <label>Easting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Extends_RC01_Highways_Defects__c.field-meta.xml
<CustomField>
    <fullName>Extends_RC01_Highways_Defects__c</fullName>
    <description>Condition of road</description>
    <label>Highway Defects</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pothole</fullName>
            </value>
            <value>
                <fullName>Obstruction</fullName>
            </value>
            <value>
                <fullName>Cracked or Damaged</fullName>
            </value>
            <value>
                <fullName>Mud on Road</fullName>
            </value>
            <value>
                <fullName>Spill, Oil or Diesel</fullName>
            </value>
            <value>
                <fullName>Damaged Speed Bumps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/lat__c.field-meta.xml
<CustomField>
    <fullName>lat__c</fullName>
    <description>Latitude</description>
    <label>lat</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>CST Described Location</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/long__c.field-meta.xml
<CustomField>
    <fullName>long__c</fullName>
    <description>Longitude</description>
    <label>long</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Northing__c.field-meta.xml
<CustomField>
    <fullName>Northing__c</fullName>
    <label>Northing</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/requested_datetime__c.field-meta.xml
<CustomField>
    <fullName>requested_datetime__c</fullName>
    <label>Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Area</label>
    <referenceTo>FixMyStreetCategories__c</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/SiteCode__c.field-meta.xml
<CustomField>
    <fullName>SiteCode__c</fullName>
    <label>SiteCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/recordTypes/RC01.recordType-meta.xml
<RecordType>
    <fullName>RC01</fullName>
    <active>true</active>
    <label>RC01</label>
</RecordType>

force-app/main/default/objects/FixMyStreetCategories__c/FixMyStreetCategories__c.object-meta.xml
<CustomObject>
    <description>A holding table of FixMyStreet Categories</description>
    <label>FixMyStreetCategories</label>
    <nameField>
        <label>FixMyStreetCategories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FixMyStreetCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Send_to_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Confirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Confirm</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <label>Service Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreetToConfirm__c/FixMyStreetToConfirm__c.object-meta.xml
<CustomObject>
    <label>FixMyStreetToConfirm</label>
    <nameField>
        <displayFormat>FMS-Confirm-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreetToConfirm</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreetToConfirm__c/fields/FixMyStreetCategories__c.field-meta.xml
<CustomField>
    <fullName>FixMyStreetCategories__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FixMyStreetCategories</label>
    <referenceTo>FixMyStreetCategories__c</referenceTo>
    <relationshipLabel>FixMyStreetToConfirm</relationshipLabel>
    <relationshipName>FixMyStreetToConfirm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreetToConfirm__c/fields/SecondField__c.field-meta.xml
<CustomField>
    <fullName>SecondField__c</fullName>
    <label>SecondField</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfirmWebService_Test.cls
@isTest
public class ConfirmWebService_Test {
 

    
    @isTest
    static void tests() {
        
             // create a case
        FixMyStreetCategories__c fixmystCat = new FixMyStreetCategories__c(
			service_code__c = 'RC01'
            );
		insert fixmystCat;
        
      //SELECT service_code__c FROM FixMyStreetCategories__c where Live__C=true and Id=:FixMyStreetId
      Object res  =  ConfirmWebService.GetFixMyStreetExtends(fixmystCat.Id);
 
        
        
       FixMyStreetCategories__c fixmystCat1 = new FixMyStreetCategories__c(
			service_code__c = 'RC01',
            Send_to_Confirm__c = true
            );
		insert fixmystCat1;
          
      Object res1  =  ConfirmWebService.GetFixMyStreetExtends(fixmystCat1.Id);
        
        
     
     
FixMyStreetToConfirm__c fixmyConfirmObj = new   FixMyStreetToConfirm__c(
	FixMyStreetCategories__c = fixmystCat1.Id,
    SecondField__c = 'Extends_RC01_Highways_Defects__c'
);                      
		insert fixmyConfirmObj;
     
     // create a case
        FixMyStreet__c fixmyObj = new FixMyStreet__c(
          Service_Area__c = fixmystCat1.Id,
          title__c = 'test'  ,
          Description__c = 'test',
          Easting__c = 123, 
          Northing__c = 123,
          Contact_Name__c = 'test',
          Contact_Phone__c = 'test',
          Contact_Email__c = 'test@test.com',
          lat__c = 1.1, 
          long__c = 1.1,
           Location__c = 'test', 
            SiteCode__c = '123',
            ConfirmReference__c = '',
            Extends_RC01_Highways_Defects__c = 'Pothole',
            requested_datetime__c = DateTime.now()
        );
		insert fixmyObj;
        
        ConfirmWebService.NewConfirmEnquiryFromId(fixmyObj.Id, false);
        ConfirmWebService.NewConfirmEnquiryFromId(fixmyObj.Id, true);


     // create a case
        FixMyStreet__c fixmyObj1 = new FixMyStreet__c(
          Service_Area__c = fixmystCat1.Id,
          title__c = 'test'  ,
          Description__c = 'test',

          Contact_Name__c = 'test',
          Contact_Phone__c = 'test',
          Contact_Email__c = 'test@test.com',
          lat__c = 1.1, 
          long__c = 1.1,
           Location__c = 'test', 
            ConfirmReference__c = '',
            Extends_RC01_Highways_Defects__c = 'Pothole',
            requested_datetime__c = DateTime.now()
        );
		insert fixmyObj1;
        
        ConfirmWebService.NewConfirmEnquiryFromId(fixmyObj1.Id,false);
        ConfirmWebService.NewConfirmEnquiryFromId(fixmyObj1.Id,true);
        

    }
}