force-app/main/default/objects/Case/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <label>Service Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult Social Care</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Blue Badges</fullName>
            </value>
            <value>
                <fullName>Children Social Care</fullName>
            </value>
            <value>
                <fullName>Council Tax</fullName>
            </value>
            <value>
                <fullName>Democratic services</fullName>
            </value>
            <value>
                <fullName>Elections</fullName>
            </value>
            <value>
                <fullName>Environmental issues</fullName>
            </value>
            <value>
                <fullName>Highways</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Registrars</fullName>
            </value>
            <value>
                <fullName>School Admissions</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Waste</fullName>
            </value>
            <value>
                <fullName>Street Scene</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FixMyStreet.recordType-meta.xml
<RecordType>
    <fullName>FixMyStreet</fullName>
    <active>true</active>
    <businessProcess>FixMyStreetProcess</businessProcess>
    <description>FixMyStreet Records</description>
    <label>FixMyStreet</label>
</RecordType>

force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/lat__c.field-meta.xml
<CustomField>
    <fullName>lat__c</fullName>
    <description>Latitude</description>
    <label>lat</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>CST Described Location</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/long__c.field-meta.xml
<CustomField>
    <fullName>long__c</fullName>
    <description>Longitude</description>
    <label>long</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/requested_datetime__c.field-meta.xml
<CustomField>
    <fullName>requested_datetime__c</fullName>
    <label>Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Area</label>
    <referenceTo>FixMyStreetCategories__c</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Investigating</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Action scheduled</fullName>
            </value>
            <value>
                <fullName>No further action</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not responsible</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Internal referral</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/FixMyStreetCategories__c.object-meta.xml
<CustomObject>
    <description>A holding table of FixMyStreet Categories</description>
    <label>FixMyStreetCategories</label>
    <nameField>
        <label>FixMyStreetCategories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FixMyStreetCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Street_LLPG__c/Street_LLPG__c.object-meta.xml
<CustomObject>
    <label>Street_LLPG</label>
    <nameField>
        <label>Street_LLPG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Street_LLPG</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Street_LLPG__c/fields/Lat__c.field-meta.xml
<CustomField>
    <fullName>Lat__c</fullName>
    <label>Lat</label>
    <precision>10</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Street_LLPG__c/fields/Long__c.field-meta.xml
<CustomField>
    <fullName>Long__c</fullName>
    <label>Long</label>
    <precision>10</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Street_LLPG__c/fields/site_code__c.field-meta.xml
<CustomField>
    <fullName>site_code__c</fullName>
    <label>site_code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Street_LLPG__c/fields/Xstart__c.field-meta.xml
<CustomField>
    <fullName>Xstart__c</fullName>
    <label>Xstart</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Street_LLPG__c/fields/Ystart__c.field-meta.xml
<CustomField>
    <fullName>Ystart__c</fullName>
    <label>Ystart</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StreetLLPGController.cls
public class StreetLLPGController {

    @AuraEnabled
    public static List<FixMyStreet__c> GetStreetSceneHistory (Id ServiceArea) {
        List<FixMyStreet__c> streetsceneHistory;
        //streetsceneHistory = [SELECT id, Name, requested_datetime__c,Location__c,Status__c,Service_Area__c, Case__r.CreatedDate FROM FixMyStreet__c WHERE Service_Area__c =: ServiceArea order by Case__r.CreatedDate DESC LIMIT 5];
        //streetsceneHistory = [SELECT id, Name,Location__c,Status__c,Service_Area__c, Case__r.CreatedDate FROM FixMyStreet__c WHERE Service_Area__c =: ServiceArea ORDER BY Case__r.CreatedDate DESC LIMIT 10];
        streetsceneHistory = [SELECT id, Name, lat__c, long__c, requested_datetime__c,Location__c,Status__c,Service_Area__c,Service_Area__r.Name, Case__r.CreatedDate FROM FixMyStreet__c where Service_area__c =: ServiceArea AND requested_datetime__c!=null order by requested_datetime__c DESC LIMIT 5];
        return streetsceneHistory;
    }
    
    
@AuraEnabled
public static Street_LLPG__c getStreetInfo(Id StreetId) {
    List<Street_LLPG__c> result = [SELECT id, site_code__c,Xstart__c,Ystart__c  FROM Street_LLPG__c WHERE Id = : StreetId];
    System.debug(result);
    


        string X =   String.valueOf(result[0].Xstart__c);
        string Y =   String.valueOf(result[0].Ystart__c);
    
     //   string lat =   String.valueOf(fixmystreet.lat__c);
     //   string lng =   String.valueOf(fixmystreet.long__c);
        
        string url = 'https://www.bgs.ac.uk/data/webservices/CoordConvert_LL_BNG.cfc?method=BNGToLatLng&easting='+X+'&northing='+Y;
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
        
        req.setEndpoint(url);
        req.setMethod('POST');
        req.setHeader('Content-Length','0');

         
        

    if(!Test.isRunningTest()) {
        // under  Test we cannot make web service call outs
        try {
            res = http.send(req);
        } catch(System.CalloutException e) {
            System.debug('Callout error: '+ e);
            System.debug(res.toString());
        }        
    }
    else
            {
                res.setHeader('Content-Type', 'application/json');
                res.setBody('{"DEGMINSECLNG":{"DEGREES":-1,"SECONDS":24,"MINUTES":32},"EASTING":451030.444044407,"LONGITUDE":-1.54,"ERROR":false,"DEGMINSECLAT":{"DEGREES":-5,"SECONDS":0,"MINUTES":33},"NORTHING":-6141064.83570885,"LATITUDE":-5.55} ');
                res.setStatusCode(200);
            } 
        
        
        System.debug(res.getBody());

        Map<String, Object> m = (Map<String, object>) JSON.deserializeUntyped(res.getBody());
        System.debug('------');
        System.debug(m);
        System.debug('------');
        System.debug(m.keySet());
        System.debug(m.get('LATITUDE'));
        System.debug(m.get('LONGITUDE'));
        
        // when the record is returned a unique payment reference is created
        Double Lat = Double.valueOf(m.get('LATITUDE'));
        Double Lng = Double.valueOf(m.get('LONGITUDE'));
        
        System.debug(Lat);
        System.debug(Lng);
        
        result[0].Lat__c =  Lat;
    	result[0].Long__c =  Lng;
         upsert result;                               
    
    
    return result[0];
}
        
}