force-app/main/default/objects/Case/recordTypes/FixMyStreet.recordType-meta.xml
<RecordType>
    <fullName>FixMyStreet</fullName>
    <active>true</active>
    <businessProcess>FixMyStreetProcess</businessProcess>
    <description>FixMyStreet Records</description>
    <label>FixMyStreet</label>
</RecordType>

force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/New_update_Comments__c.field-meta.xml
<CustomField>
    <fullName>New_update_Comments__c</fullName>
    <label>New update Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Investigating</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Action scheduled</fullName>
            </value>
            <value>
                <fullName>No further action</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not responsible</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Internal referral</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Update_FixMyStreet__c.field-meta.xml
<CustomField>
    <fullName>Update_FixMyStreet__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Setting this will ensure that changes to fields is sent to FixMyStreet</inlineHelpText>
    <label>Update FixMyStreet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Updates__mdt/FixMyStreet_Updates__mdt.object-meta.xml
<CustomObject>
    <label>FixMyStreet Updates</label>
    <pluralLabel>FixMyStreet Updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/FixMyStreet_Updates__mdt/fields/FMS_Status__c.field-meta.xml
<CustomField>
    <fullName>FMS_Status__c</fullName>
    <label>FMS Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Updates__mdt/fields/Update_Text__c.field-meta.xml
<CustomField>
    <fullName>Update_Text__c</fullName>
    <label>Update Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/FixMyStreetCommentsStatusChange.cls
global with sharing class FixMyStreetCommentsStatusChange {


	@InvocableMethod(label='FixMyStreet Comments from Case' description='Used to add updates when the case status changes')
    public static void doCommentsFromCase(List<FMSRequests> requests) {

        
        if (requests == null)
       {
           system.debug('No id sent to doCommentsFromCase');
           return;
       }

        FMSRequests firstRequest = requests[0];
        
       Id caseId = firstRequest.caseId;
       system.debug('Add comments for  '+ caseId);
        addCommentsFromCase(caseId);
    }

    
    global  class FMSRequests {
        @InvocableVariable
        global Id caseId;
    }

    public static void addCommentsFromCase(Id caseId) {


    // get case status
    Case caseDetails = [SELECT Status FROM Case where Id =: caseId LIMIT 1];


    // get the FixMyStreet info
    List<FixMyStreet__c> fms = [SELECT Id,New_update_Comments__c,Name, Status__c from FixMyStreet__c WHERE Case__c=: caseId LIMIT 1];

    // search for say 'Case - Investigating'
    string findCaseStatus = 'Case - '+caseDetails.Status;

    List<FixMyStreet_Updates__mdt> fms_Status_Description = [SELECT MasterLabel, Update_Text__c, FMS_Status__c  FROM FixMyStreet_Updates__mdt WHERE MasterLabel = :findCaseStatus LIMIT 1];

    
    if (fms_Status_Description.size() != 0  && fms.size() != 0)
        {
        string newComments = fms_Status_Description[0].Update_Text__c;
        system.debug(newComments);

        FixMyStreet__c fmsUpdate = fms[0];
        fmsUpdate.Update_FixMyStreet__c = true;

        fmsUpdate.New_update_Comments__c = newComments;
        if (fms_Status_Description[0].FMS_Status__c != null)
            {
            fmsUpdate.Status__c = fms_Status_Description[0].FMS_Status__c;
            }
        upsert fmsUpdate;
        }

    }
}