force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/agency_responsible__c.field-meta.xml
<CustomField>
    <fullName>agency_responsible__c</fullName>
    <label>agency_responsible</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/detail__c.field-meta.xml
<CustomField>
    <fullName>detail__c</fullName>
    <label>detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/requested_datetime__c.field-meta.xml
<CustomField>
    <fullName>requested_datetime__c</fullName>
    <label>Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Area</label>
    <referenceTo>FixMyStreetCategories__c</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Investigating</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Action scheduled</fullName>
            </value>
            <value>
                <fullName>No further action</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not responsible</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Internal referral</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Update_Comments__c.field-meta.xml
<CustomField>
    <fullName>Update_Comments__c</fullName>
    <label>Update Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/FixMyStreetCategories__c.object-meta.xml
<CustomObject>
    <description>A holding table of FixMyStreet Categories</description>
    <label>FixMyStreetCategories</label>
    <nameField>
        <label>FixMyStreetCategories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FixMyStreetCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Send_to_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Confirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Confirm</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <label>Service Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FixMyStreetTestManager.cls
@istest(SeeAllData=true)
public class FixMyStreetTestManager {
 
   static testMethod void  testgetFixMyStreet_All(){
   
         
   Test.startTest();
   
   //As Per Best Practice it is important to instantiate the Rest Context 
   
   RestRequest req = new RestRequest(); 
   RestResponse res = new RestResponse();
         
   req.requestURI = '/services/apexrest/FixMyStreet';  //Request URL
   req.httpMethod = 'GET';//HTTP Request Type
   req.addParameter('all', 'yes');
   //req.requestBody = Blob.valueof(JsonMsg);
   RestContext.request = req;
   RestContext.response= res;


   List<FixMyStreet__c> result = FixMyStreetManager.getFixMyStreet(); //Call the Method of the Class with Proper       Constructor 
   
      System.debug(result);
       
   //System.assert(resp.statusMessage.contains('Test success message'));//Assert the response has message as expected 
   //System.assert(resp.statusCode.contains('Done'));
   //System.assert(resp.acct.Id!=null);//Assert that the Account is inserted and has Id
   Test.stopTest();
  
   }
    
   static testMethod void  testgetFixMyStreet_id(){
   
         
   Test.startTest();
   
   //As Per Best Practice it is important to instantiate the Rest Context 
   
   RestRequest req = new RestRequest(); 
   RestResponse res = new RestResponse();
         
   req.requestURI = '/services/apexrest/FixMyStreet';  //Request URL
   req.httpMethod = 'GET';//HTTP Request Type
   req.addParameter('id', 'yes');
   //req.requestBody = Blob.valueof(JsonMsg);
   RestContext.request = req;
   RestContext.response= res;


   List<FixMyStreet__c> result = FixMyStreetManager.getFixMyStreet(); //Call the Method of the Class with Proper       Constructor 
   
      System.debug(result);
       
   //System.assert(resp.statusMessage.contains('Test success message'));//Assert the response has message as expected 
   //System.assert(resp.statusCode.contains('Done'));
   //System.assert(resp.acct.Id!=null);//Assert that the Account is inserted and has Id
   Test.stopTest();
  
   }

   static testMethod void  testgetFixMyStreet_name(){
   
         
   Test.startTest();
   
   //As Per Best Practice it is important to instantiate the Rest Context 
   
   RestRequest req = new RestRequest(); 
   RestResponse res = new RestResponse();
         
   req.requestURI = '/services/apexrest/FixMyStreet';  //Request URL
   req.httpMethod = 'GET';//HTTP Request Type
   req.addParameter('name', 'yes');
   //req.requestBody = Blob.valueof(JsonMsg);
   RestContext.request = req;
   RestContext.response= res;


   List<FixMyStreet__c> result = FixMyStreetManager.getFixMyStreet(); //Call the Method of the Class with Proper       Constructor 
   
      System.debug(result);
       
   //System.assert(resp.statusMessage.contains('Test success message'));//Assert the response has message as expected 
   //System.assert(resp.statusCode.contains('Done'));
   //System.assert(resp.acct.Id!=null);//Assert that the Account is inserted and has Id
   Test.stopTest();
  
   }
    
   static testMethod void  testgetFixMyStreet_del(){
   
         
   Test.startTest();
   
   //As Per Best Practice it is important to instantiate the Rest Context 
   
   RestRequest req = new RestRequest(); 
   RestResponse res = new RestResponse();
         
   req.requestURI = '/services/apexrest/FixMyStreet';  //Request URL
   req.httpMethod = 'GET';//HTTP Request Type
   req.addParameter('del', 'yes');
   //req.requestBody = Blob.valueof(JsonMsg);
   RestContext.request = req;
   RestContext.response= res;


   List<FixMyStreet__c> result = FixMyStreetManager.getFixMyStreet(); //Call the Method of the Class with Proper       Constructor 
   
      System.debug(result);
       
   //System.assert(resp.statusMessage.contains('Test success message'));//Assert the response has message as expected 
   //System.assert(resp.statusCode.contains('Done'));
   //System.assert(resp.acct.Id!=null);//Assert that the Account is inserted and has Id
   Test.stopTest();
  
   }
    
   static testMethod void  testgetFixMyStreet_dellall(){
   
         
   Test.startTest();
   
   //As Per Best Practice it is important to instantiate the Rest Context 
   
   RestRequest req = new RestRequest(); 
   RestResponse res = new RestResponse();
         
   req.requestURI = '/services/apexrest/FixMyStreet';  //Request URL
   req.httpMethod = 'GET';//HTTP Request Type
   req.addParameter('delall', 'confirm');
   //req.requestBody = Blob.valueof(JsonMsg);
   RestContext.request = req;
   RestContext.response= res;


   List<FixMyStreet__c> result = FixMyStreetManager.getFixMyStreet(); //Call the Method of the Class with Proper       Constructor 
   
      System.debug(result);
       
   //System.assert(resp.statusMessage.contains('Test success message'));//Assert the response has message as expected 
   //System.assert(resp.statusCode.contains('Done'));
   //System.assert(resp.acct.Id!=null);//Assert that the Account is inserted and has Id
   Test.stopTest();
  
   }    
    
   
   static testMethod void  testcreateFixMyStreet(){
   
         
   Test.startTest();
       
    FixMyStreetCategories__c  tempService = new FixMyStreetCategories__c (
        	Name = 'Test Service',
    		Service_Code__c = 'Temp',
        	Send_to_Confirm__c = false
    );
    insert tempService;
   
        
       //As Per Best Practice it is important to instantiate the Rest Context 
   
   RestRequest req = new RestRequest(); 
   RestResponse res = new RestResponse();
         
  List<string> photolist = new List<string>();
       photolist.add('1');
       photolist.add('2');

            
    JSONGenerator generator = JSON.createGenerator(true); 	
    generator.writeStartObject(); 				
    generator.writeStringField('agency_responsible__c', 'Rutland County Council');  	 
    generator.writeStringField('description__c', 'Test');  	
    generator.writeStringField('detail__c', 'Test');  	
    generator.writeStringField('Service_Area__c', tempService.Id);  	
   // generator.writeStringField('id', 'a086E000001yIG0QAM');
    generator.writeStringField('status__c', 'open');  	
    generator.writeStringField('update_comments__c','test');
    generator.writeStringField('requested_datetime__c', '2017-12-08T09:47:35.000+0000');

    generator.writeObjectField ('photos', photolist);

  
    generator.writeEndObject(); 				
    String jsonString = generator.getAsString();  
    jsonString = '[' + jsonString + ']';   
    system.debug(jsonString);   
  
       
   req.requestURI = '/services/apexrest/FixMyStreet';  //Request URL
   req.httpMethod = 'POST';//HTTP Request Type
   req.requestBody = Blob.valueof(jsonString);
   RestContext.request = req;
   RestContext.response= res;


   FixMyStreetManager.createFixMyStreet(); //Call the Method of the Class with Proper       Constructor 
       
   //System.assert(resp.statusMessage.contains('Test success message'));//Assert the response has message as expected 
   //System.assert(resp.statusCode.contains('Done'));
   //System.assert(resp.acct.Id!=null);//Assert that the Account is inserted and has Id
   Test.stopTest();
  
   }
    


  static testMethod void  testcreateFixMyStreetUpdate(){
   
         
   Test.startTest();
   
    FixMyStreetCategories__c  tempService = new FixMyStreetCategories__c (
        	Name = 'Test Service',
    		Service_Code__c = 'Temp',
        	Send_to_Confirm__c = false
    );
    insert tempService;
      
     
    // create a service requets to update
    FixMyStreet__c  tempFixMyStreet = new FixMyStreet__c (
        	title__c = 'Test Service',
    		Service_Area__c = tempService.Id
    );
    insert tempFixMyStreet;    
     
     //As Per Best Practice it is important to instantiate the Rest Context 
   
   RestRequest req = new RestRequest(); 
   RestResponse res = new RestResponse();
         
 

            
    JSONGenerator generator = JSON.createGenerator(true); 	
    generator.writeStartObject(); 				
    generator.writeStringField('agency_responsible__c', 'Rutland County Council');  	 
    generator.writeStringField('description__c', 'Test');  	
    generator.writeStringField('detail__c', 'Test');  	
    //generator.writeStringField('Service_Area__c', 'a096E000007q6HzQAI');  	
    generator.writeStringField('id', tempFixMyStreet.Id);
    generator.writeStringField('status__c', 'open');  	
    generator.writeStringField('update_comments__c','test');
    generator.writeStringField('requested_datetime__c', '2017-12-08T09:47:35.000+0000');
    generator.writeFieldName('photos');
    generator.writeStartObject();
    generator.writeStringField('photourl', 'photurl');
    generator.writeEndObject();
  
    generator.writeEndObject(); 				
    String jsonString = generator.getAsString();  
    jsonString = '[' + jsonString + ']';   
    system.debug(jsonString);   
       
   req.requestURI = '/services/apexrest/FixMyStreet';  //Request URL
   req.httpMethod = 'POST';//HTTP Request Type
   req.requestBody = Blob.valueof(jsonString);
   RestContext.request = req;
   RestContext.response= res;


   FixMyStreetManager.createFixMyStreet(); //Call the Method of the Class with Proper       Constructor 
       
   //System.assert(resp.statusMessage.contains('Test success message'));//Assert the response has message as expected 
   //System.assert(resp.statusCode.contains('Done'));
   //System.assert(resp.acct.Id!=null);//Assert that the Account is inserted and has Id
   Test.stopTest();
  
   }        
    
     static testMethod void  testcreateFixMyStreetUpdateID(){
   
         
   Test.startTest();
   
   //As Per Best Practice it is important to instantiate the Rest Context 
   
   RestRequest req = new RestRequest(); 
   RestResponse res = new RestResponse();
         
 

            
    JSONGenerator generator = JSON.createGenerator(true); 	
    generator.writeStartObject(); 				
    generator.writeStringField('agency_responsible__c', 'Rutland County Council');  	 
    generator.writeStringField('description__c', 'Test');  	
    generator.writeStringField('detail__c', 'Test');  	
    generator.writeStringField('Service_Area__c', 'a096E000007q6HzQAI');  	
    generator.writeStringField('Id', 'a086E000001yIG0QAM');
    generator.writeStringField('status__c', 'open');  	
    generator.writeStringField('update_comments__c','test');
    generator.writeStringField('requested_datetime__c', '2017-12-08T09:47:35.000+0000');
    generator.writeFieldName('photos');
    generator.writeStartObject();
    generator.writeStringField('photourl', 'photurl');
    generator.writeEndObject();
  
    generator.writeEndObject(); 				
    String jsonString = generator.getAsString();  
    jsonString = '[' + jsonString + ']';   
    system.debug(jsonString);   
       
   req.requestURI = '/services/apexrest/FixMyStreet';  //Request URL
   req.httpMethod = 'POST';//HTTP Request Type
   req.requestBody = Blob.valueof(jsonString);
   RestContext.request = req;
   RestContext.response= res;


   FixMyStreetManager.createFixMyStreet(); //Call the Method of the Class with Proper       Constructor 
       
   //System.assert(resp.statusMessage.contains('Test success message'));//Assert the response has message as expected 
   //System.assert(resp.statusCode.contains('Done'));
   //System.assert(resp.acct.Id!=null);//Assert that the Account is inserted and has Id
   Test.stopTest();
  
   }


 }