force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Area</label>
    <referenceTo>FixMyStreetCategories__c</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/FixMyStreetCategories__c.object-meta.xml
<CustomObject>
    <description>A holding table of FixMyStreet Categories</description>
    <label>FixMyStreetCategories</label>
    <nameField>
        <label>FixMyStreetCategories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FixMyStreetCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <label>Service Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FixMyStreetChangeRecordType.cls
global with sharing class FixMyStreetChangeRecordType {

    
	@InvocableMethod
    public static void fixMyStreetChangeRecordType(List<fixMyStreetChangeRecordTypeRequests> requests) {

        
        if (requests == null)
       {
           system.debug('No id sent to fixMyStreetChangeRecordType');
           return;
       }

        fixMyStreetChangeRecordTypeRequests firstRequest = requests[0];
        
       Id fixmystreetId = firstRequest.fixmystreetId;

        // look up Service_Code of record

        FixMyStreet__c fms = [SELECT Service_Area__r.Service_Code__c, RecordTypeId FROM FixMyStreet__c WHERE Id=:fixmystreetId LIMIT 1];
        string rec = fms.Service_Area__r.Service_Code__c;

        Schema.RecordTypeInfo recordInfo = Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().getRecordTypeInfosByName().get(rec);

        if (recordInfo != null)
            {

            Id newRecordTypeId = Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().getRecordTypeInfosByName().get(rec).getRecordTypeId();

            if (newRecordTypeId != null)
                {
                fms.RecordTypeId = newRecordTypeId; 
                upsert fms;
                }
            }
    }

    
    global  class fixMyStreetChangeRecordTypeRequests {
        @InvocableVariable
        global Id fixmystreetId;
    }

}