force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/New_update_Comments__c.field-meta.xml
<CustomField>
    <fullName>New_update_Comments__c</fullName>
    <label>New update Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Investigating</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Action scheduled</fullName>
            </value>
            <value>
                <fullName>No further action</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not responsible</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Internal referral</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Update_Comments__c.field-meta.xml
<CustomField>
    <fullName>Update_Comments__c</fullName>
    <label>Update Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Update_FixMyStreet__c.field-meta.xml
<CustomField>
    <fullName>Update_FixMyStreet__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Setting this will ensure that changes to fields is sent to FixMyStreet</inlineHelpText>
    <label>Update FixMyStreet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Comments__c/FixMyStreet_Comments__c.object-meta.xml
<CustomObject>
    <label>FixMyStreet Comments</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>FixMyStreet Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet_Comments__c/fields/Comment_Date__c.field-meta.xml
<CustomField>
    <fullName>Comment_Date__c</fullName>
    <label>Comment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Comments__c/fields/Comment_Id__c.field-meta.xml
<CustomField>
    <fullName>Comment_Id__c</fullName>
    <label>Comment Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Comments__c/fields/FixMyStreet__c.field-meta.xml
<CustomField>
    <fullName>FixMyStreet__c</fullName>
    <label>FixMyStreet</label>
    <referenceTo>FixMyStreet__c</referenceTo>
    <relationshipLabel>FixMyStreet Comments</relationshipLabel>
    <relationshipName>FixMyStreet_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FixMyStreetUpdates.cls
@RestResource(urlMapping='/FixMyStreetUpdates/*')
global with sharing class FixMyStreetUpdates {

    public class Parent {
    public String id;
    public String Comments;
    public String Status;
	}

    
    @HttpGet
    global static void getFixMyStreetUpdates() {
        RestRequest request = RestContext.request;
               
        RestRequest req = RestContext.request;
        String p_updates = req.params.get('updates');
        String p_test = req.params.get('test');

 		Parent[] listResults = new Parent[] {};
 
        if (p_updates != null) {
		 		List<FixMyStreet__c> resultList =  database.query('SELECT Id,New_update_Comments__c,Update_Comments__c,status__c FROM FixMyStreet__c where Update_FixMyStreet__c=true');
             	for (FixMyStreet__c indResult: resultList) {
                    Parent p = new Parent();
                    p.id = indResult.id;
                    p.Comments = indResult.New_update_Comments__c;
                    p.Status = indResult.status__c;
            		listResults.add(p);
                    if (indResult.New_update_Comments__c != null && p_test != 'true') {
                        FixMyStreet_Comments__c newcomment = new FixMyStreet_Comments__c(
                            Comment__c = indResult.New_update_Comments__c, 
                            Comment_Id__c = 'Internal Comment',
                            Comment_Date__c = datetime.now(),
                            FixMyStreet__c= indResult.id);
                            insert newcomment;   
                         }
                    // now update clear the comments
                    indResult.New_update_Comments__c = '';
                    indResult.Update_FixMyStreet__c = false;
                    upsert indResult;
                    }       
       		 }

		string result = JSON.serializePretty(listResults);     
        RestContext.response.addHeader('Content-Type', 'application/json');
		RestContext.response.responseBody = Blob.valueOf(result);
        
        // use this updates from FixMyStreet to capture any updates from Confirm for FixMyStreet (next call)
		ConfirmUpdate.ConfirmUpdates();
        
    }


}