force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/ConfirmReference__c.field-meta.xml
<CustomField>
    <fullName>ConfirmReference__c</fullName>
    <label>ConfirmReference</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Easting__c.field-meta.xml
<CustomField>
    <fullName>Easting__c</fullName>
    <label>Easting</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/FixMyStreetURL__c.field-meta.xml
<CustomField>
    <fullName>FixMyStreetURL__c</fullName>
    <formula>HYPERLINK(&quot;https://www.fixmystreet.com/report/&quot;&amp;  TEXT(service_request_id__c) , &quot;https://www.fixmystreet.com/report/&quot;&amp;  TEXT(service_request_id__c), &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FixMyStreetURL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/lat__c.field-meta.xml
<CustomField>
    <fullName>lat__c</fullName>
    <description>Latitude</description>
    <label>lat</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>CST Described Location</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/long__c.field-meta.xml
<CustomField>
    <fullName>long__c</fullName>
    <description>Longitude</description>
    <label>long</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Northing__c.field-meta.xml
<CustomField>
    <fullName>Northing__c</fullName>
    <label>Northing</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Number_of_Photos__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Photos__c</fullName>
    <label>Number of Photos</label>
    <summaryForeignKey>FixMyStreet_Photo__c.FixMyStreet__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/requested_datetime__c.field-meta.xml
<CustomField>
    <fullName>requested_datetime__c</fullName>
    <label>Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Area</label>
    <referenceTo>FixMyStreetCategories__c</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/service_request_id__c.field-meta.xml
<CustomField>
    <fullName>service_request_id__c</fullName>
    <label>Service request id</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/SiteCode__c.field-meta.xml
<CustomField>
    <fullName>SiteCode__c</fullName>
    <label>SiteCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Comments__c/FixMyStreet_Comments__c.object-meta.xml
<CustomObject>
    <label>FixMyStreet Comments</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>FixMyStreet Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet_Comments__c/fields/Comment_Date__c.field-meta.xml
<CustomField>
    <fullName>Comment_Date__c</fullName>
    <label>Comment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Comments__c/fields/FixMyStreet__c.field-meta.xml
<CustomField>
    <fullName>FixMyStreet__c</fullName>
    <label>FixMyStreet</label>
    <referenceTo>FixMyStreet__c</referenceTo>
    <relationshipLabel>FixMyStreet Comments</relationshipLabel>
    <relationshipName>FixMyStreet_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FixMyStreetCommentsEmail.cls
global with sharing class FixMyStreetCommentsEmail {

	@InvocableMethod(label='FixMyStreet Comments Email' description='Used to send emails when comment')
    public static void doEmail(List<FMSRequests> requests) {

        
        if (requests == null)
       {
           system.debug('No id sent to doCreationConfirmRecord');
           return;
       }

        FMSRequests firstRequest = requests[0];
        
       Id fixmystreetId = firstRequest.fixmystreetId;
       String emailAddress = firstRequest.emailAddress;
       system.debug('NewEmail '+ fixmystreetId);
        SendEmail(fixmystreetId,emailAddress);
    }

    
    global  class FMSRequests {
        @InvocableVariable
        global Id fixmystreetId;
        @InvocableVariable
        global string emailAddress;
    }

    public static void SendEmail(Id fixmystreetId, string emailAdress) {

    // this is the Id of the comment
    FixMyStreet_Comments__c commentDetail = [SELECT FixMyStreet__c, Comment__c,Comment_Date__c FROM FixMyStreet_Comments__c where Id =: fixmystreetId LIMIT 1];

    string comment = '';
    string fmsSummary = '';
	FixMyStreet__c fixmystreet = null;
    if (commentDetail != null)
        {
        comment = commentDetail.Comment__c;
 
        fixmystreet = [SELECT id, Name, Service_Area__c,title__c,Description__c,Easting__c, Northing__c,
                        requested_datetime__c,Contact_Name__c,Contact_Phone__c,Contact_Email__c,
                       lat__c, long__c,
                        Location__c, SiteCode__c,
                       ConfirmReference__c,service_request_id__c,Number_of_Photos__c,FixMyStreetURL__c
                        FROM FixMyStreet__c 
                        WHERE FixMyStreet__c.id = :commentDetail.FixMyStreet__c
                        LIMIT 1
                       ];
        if (fixmystreet != null)
            {
            if (fixmystreet.ConfirmReference__c!='')
            {
            fmsSummary = fmsSummary + 'Confirm Reference: '+fixmystreet.ConfirmReference__c+'<br/>';
            }
            fmsSummary = fmsSummary + 'Reference: '+fixmystreet.Name+'<br/>';
             fmsSummary = fmsSummary + 'Title: '+fixmystreet.title__c+'<br/>';
            fmsSummary = fmsSummary + 'Link: '+fixmystreet.FixMyStreetURL__c+'<br/>';
            } 
        }

    // First, reserve email capacity for the current Apex transaction to ensure
    // that we won't exceed our daily email limits when sending email after
    // the current transaction is committed.
    Boolean proceed = false;
    try {
    Messaging.reserveSingleEmailCapacity(2);
    proceed = true;
    } catch (Exception e) {
        //handle your exception gracefully
    }
    // Processes and actions involved in the Apex transaction occur next,
    // which conclude with sending a single email.

    if (proceed)
    {
    // Now create a new single email message object
    // that will send out a single email to the addresses in the To, CC & BCC list.
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

    // Strings to hold the email addresses to which you are sending the email.
    String[] toAddresses = new String[] {'anix@rutland.gov.uk'}; 
    String[] ccAddresses = new String[] {'anix@rutland.gov.uk'};

    string orgId = UserInfo.getOrganizationId();
    system.debug('OrgId: '+orgId);
    boolean production = false;
    if (orgId == '00D0Y000002EzYY')
    {
    production = true;
    }

    if (fixmystreet != null && production == true)
    {
        if (fixmystreet.ConfirmReference__c!=''){
                toAddresses.add('rsalt@rutland.gov.uk');
            }
        else {
                toAddresses.add('bthompson@rutland.gov.uk');
                toAddresses.add('mloran@rutland.gov.uk');
                toAddresses.add('skidd@rutland.gov.uk');
            }
    }
 

    // Assign the addresses for the To and CC lists to the mail object.
    mail.setToAddresses(toAddresses);
    mail.setCcAddresses(ccAddresses);

    // Specify the address used when the recipients reply to the email. 
    mail.setReplyTo('anix@rutland.gov.uk');

    // Specify the name used as the display name.
    mail.setSenderDisplayName('Salesforce');

    // Specify the subject line for your email address.
    mail.setSubject('New Comment on FixMyStreet Entry');

    // Set to True if you want to BCC yourself on the email.
    mail.setBccSender(false);

    // Optionally append the salesforce.com email signature to the email.
    // The email address of the user executing the Apex Code will be used.
    mail.setUseSignature(false);

    // Specify the text content of the email.
    mail.setPlainTextBody('FixMyStreet Details'+fmsSummary+'Comments'+ comment);

    mail.setHtmlBody('<b>FixMyStreet Details</b><br/>'+fmsSummary+'<b>Comments</b><br/>'+ comment);

    // Send the email you have created.
    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    }
}