force-app/main/default/objects/FixMyStreet__c/FixMyStreet__c.object-meta.xml
<CustomObject>
    <description>FixMyStreet Requests</description>
    <label>FixMyStreet</label>
    <nameField>
        <displayFormat>FMS-RCC-{00000}</displayFormat>
        <label>FixMyStreet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet__c/fields/agency_responsible__c.field-meta.xml
<CustomField>
    <fullName>agency_responsible__c</fullName>
    <label>agency_responsible</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/agency_sent_datetime__c.field-meta.xml
<CustomField>
    <fullName>agency_sent_datetime__c</fullName>
    <inlineHelpText>DateTime of fixmystreet entry format 2017-11-27T20:30:11.837838+00:00</inlineHelpText>
    <label>Agency Sent Date Stamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/detail__c.field-meta.xml
<CustomField>
    <fullName>detail__c</fullName>
    <label>detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/interface_used__c.field-meta.xml
<CustomField>
    <fullName>interface_used__c</fullName>
    <inlineHelpText>How the FixMyStreet came to us</inlineHelpText>
    <label>Interface Used</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/lat__c.field-meta.xml
<CustomField>
    <fullName>lat__c</fullName>
    <description>Latitude</description>
    <label>lat</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/long__c.field-meta.xml
<CustomField>
    <fullName>long__c</fullName>
    <description>Longitude</description>
    <label>long</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/New_update_Comments__c.field-meta.xml
<CustomField>
    <fullName>New_update_Comments__c</fullName>
    <label>New update Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/requested_datetime__c.field-meta.xml
<CustomField>
    <fullName>requested_datetime__c</fullName>
    <label>Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/requestor_name__c.field-meta.xml
<CustomField>
    <fullName>requestor_name__c</fullName>
    <label>Requestor Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Service_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Area</label>
    <referenceTo>FixMyStreetCategories__c</referenceTo>
    <relationshipLabel>FixMyStreet</relationshipLabel>
    <relationshipName>FixMyStreet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/service_request_id__c.field-meta.xml
<CustomField>
    <fullName>service_request_id__c</fullName>
    <label>Service request id</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Investigating</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Action scheduled</fullName>
            </value>
            <value>
                <fullName>No further action</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not responsible</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Internal referral</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Update_Comments__c.field-meta.xml
<CustomField>
    <fullName>Update_Comments__c</fullName>
    <label>Update Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Update_Comments_Id__c.field-meta.xml
<CustomField>
    <fullName>Update_Comments_Id__c</fullName>
    <label>Update Comments Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/Update_FixMyStreet__c.field-meta.xml
<CustomField>
    <fullName>Update_FixMyStreet__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Setting this will ensure that changes to fields is sent to FixMyStreet</inlineHelpText>
    <label>Update FixMyStreet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FixMyStreet__c/fields/updated_datetime__c.field-meta.xml
<CustomField>
    <fullName>updated_datetime__c</fullName>
    <label>Updated datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Comments__c/FixMyStreet_Comments__c.object-meta.xml
<CustomObject>
    <label>FixMyStreet Comments</label>
    <nameField>
        <displayFormat>Comment-{00000}</displayFormat>
        <label>FixMyStreet Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet_Comments__c/fields/Comment_Date__c.field-meta.xml
<CustomField>
    <fullName>Comment_Date__c</fullName>
    <label>Comment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Comments__c/fields/Comment_Id__c.field-meta.xml
<CustomField>
    <fullName>Comment_Id__c</fullName>
    <label>Comment Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Comments__c/fields/FixMyStreet__c.field-meta.xml
<CustomField>
    <fullName>FixMyStreet__c</fullName>
    <label>FixMyStreet</label>
    <referenceTo>FixMyStreet__c</referenceTo>
    <relationshipLabel>FixMyStreet Comments</relationshipLabel>
    <relationshipName>FixMyStreet_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Photo__c/FixMyStreet_Photo__c.object-meta.xml
<CustomObject>
    <description>List of photos</description>
    <label>FixMyStreet Photo</label>
    <nameField>
        <displayFormat>FMSP-{0000}</displayFormat>
        <label>FixMyStreet Photo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FixMyStreet Photos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreet_Photo__c/fields/FixMyStreet__c.field-meta.xml
<CustomField>
    <fullName>FixMyStreet__c</fullName>
    <label>FixMyStreet</label>
    <referenceTo>FixMyStreet__c</referenceTo>
    <relationshipLabel>FixMyStreet Photos</relationshipLabel>
    <relationshipName>FixMyStreet_Photos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Photo__c/fields/Photo_Link__c.field-meta.xml
<CustomField>
    <fullName>Photo_Link__c</fullName>
    <label>Photo_Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/FixMyStreet_Updates__mdt/FixMyStreet_Updates__mdt.object-meta.xml
<CustomObject>
    <label>FixMyStreet Updates</label>
    <pluralLabel>FixMyStreet Updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/FixMyStreet_Updates__mdt/fields/Update_Text__c.field-meta.xml
<CustomField>
    <fullName>Update_Text__c</fullName>
    <label>Update Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FixMyStreetCategories__c/FixMyStreetCategories__c.object-meta.xml
<CustomObject>
    <description>A holding table of FixMyStreet Categories</description>
    <label>FixMyStreetCategories</label>
    <nameField>
        <label>FixMyStreetCategories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FixMyStreetCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FixMyStreetCategories__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <label>Service Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FixMyStreetManager.cls
@RestResource(urlMapping='/FixMyStreet/*')
global with sharing class FixMyStreetManager {

    @HttpGet
    global static List<FixMyStreet__c> getFixMyStreet() {
        RestRequest request = RestContext.request;
        
        List<FixMyStreet__c> result = null;
 
 		//get object fields
        List<String> fieldList = new List<String>(Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().fields.getMap().keySet());
        String fields = String.join(fieldList,',');       
        
        RestRequest req = RestContext.request;
        String p_id = req.params.get('id');
        String p_del = req.params.get('del');
        String p_delall = req.params.get('delall');
        String p_all = req.params.get('all');
        String p_name = req.params.get('name');

       
        if (p_id != null) {
 		 		//result =  database.query('SELECT title__c,agency_sent_datetime__c,agency_responsible__c,description__c,detail__c,interface_used__c,lat__c,long__c,requested_datetime__c,requestor_name__c,service_code__c,service_name__c,service_request_id__c,status__c,updated_datetime__c FROM FixMyStreet__c where Id = :p_id');
 		 		result =  database.query('SELECT '+fields+' FROM FixMyStreet__c where Id = :p_id');
        } else if (p_name != null) {
 		 		result =  database.query('SELECT '+fields+' FROM FixMyStreet__c where name = :p_name');
        } 
        else if (p_all != null) {
 		 		result =  database.query('SELECT '+fields+' FROM FixMyStreet__c');
        } else if (p_del != null) {
 		 	result =  database.query('SELECT Id FROM FixMyStreet__c where Id = :p_del');
            delete result;
        }
        else if (p_delall != null) {
           if (p_delall == 'Confirm')
            {
 		 	result =  database.query('SELECT Id FROM FixMyStreet__c');
            delete result;
            }    
        }
        
        return result;
    }

    global class FixMyStreet{
        public String title;
    }
    
    @HttpPost
    global static void createFixMyStreet()
    {
        //get object fields
        List<String> fieldList = new List<String>(Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().fields.getMap().keySet());
        String fields = String.join(fieldList,',');   
        //fields = fields.toLowerCase();
           
        
		string result = '';
        List<Id> retid = new List<Id>();
        
        string body = RestContext.request.requestBody.toString();
        //body = body.toLowerCase();
        
        List<Object> requestList = (List<Object>) JSON.deserializeUntyped(body);
        
        for (Object requestObject : requestList)
        {
        Map<String, Object> m =  (Map<String, Object>) requestObject;        

        
        
      	if (m.get('Id') != null || m.get('id') != null)
            {
                //do updated not insert
                string fixId = '';
                if (m.get('Id') != null)
            		{
                    fixId = (string) m.get('Id');
                    }
                else
                    {
                    fixId = (string) m.get('id');
                    }
                system.debug('Updating id: '+fixID);
				system.debug('Status__c: ' +m.get('status__c'));
                system.debug('Making call to look up entry to update');
                
                List<FixMyStreet__c> fixs =  database.query('SELECT status__c, Update_Comments__c FROM FixMyStreet__c where Id = :fixId');
 				// check if results
            	FixMyStreet__c fix = null;
                if (fixs.size()>0)
                {
                    fix = fixs[0];
                    system.debug('Updating entry');
                    system.debug(fix);
                    
                    if (m.get('status__c') != null)
                    {
                        fix.status__c = (string) m.get('status__c');
                        upsert fix;
                    }   
                    retid.add(fix.Id);
                    // add new comment to related comments list
                    if (m.get('update_comments__c') != null)
                    {
                        FixMyStreet_Comments__c newcomment = new FixMyStreet_Comments__c(
                            Comment__c = (string) m.get('update_comments__c'), 
                            Comment_Id__c = (string) m.get('update_comments_id__c'),
                            Comment_Date__c = datetime.now(),
                            FixMyStreet__c=fixId);
                        insert newcomment;           
                    }
                    // end of update   
                }
            }
       		else
       		{
			// new entry
            FixMyStreet__c fix = new FixMyStreet__c();
            // iterate through the fields on the main record to match to the incoming JSON
            // default status to Open
            fix.Status__c = 'Open';
            for (string field : fieldList)
            {
             //   system.debug(field);
             //   system.debug(m.get(field));
                if(m.get(field) != null){
                    if (field == 'requested_datetime__c' || field == 'updated_datetime__c' || field == 'agency_sent_datetime__c')
                        {
                        string fieldst = (string) m.get(field);
                        DateTime dt = (DateTime) JSON.deserialize('"' + fieldst + '"', DateTime.class);
                        fix.put(field, dt);
                        }
                    else
                        {
                        fix.put(field, m.get(field));
                        }
                    }
            }
   
            // the Service_Area__c needs matching
            string serv = (string) m.get('Service_Area__c');
                system.debug(serv);
            //FixMyStreetCategories__c service = database.query('select Id from FixMyStreetCategories__c where Id= :serv');
              //  system.debug(service);
            //fix.Service_Area__c  = service.Id;
            fix.Service_Area__c  = serv;
           // system.debug(fix);

                // add a standard comment response to go back...next time
                string code = '1000';
                //FixMyStreet_Updates__mdt fms_Update;
                List<FixMyStreet_Updates__mdt> fms_Updates = [SELECT MasterLabel, Update_Text__c  FROM FixMyStreet_Updates__mdt WHERE MasterLabel = :code LIMIT 1];
                if (fms_Updates.size() == 1)
                	{
                	string newComments = fms_Updates[0].Update_Text__c;
                	system.debug(newComments);
                	fix.New_update_Comments__c = newComments;
                	fix.Update_FixMyStreet__c = true;
                	fix.Status__c = 'Investigating';
                    }
                
            insert fix;
            // photos need importing
                
			if (m.get('photos') != null)
                {
	 			List<Object> urls =  (List<Object>) m.get('photos'); 
    	        for (Object a: urls)
	        	    {
    	        	string photourl = (string) a;
                        FixMyStreet_Photo__c newphoto = new FixMyStreet_Photo__c();
                        //newphoto.Name = (string) mphoto.get('Name');
                        newphoto.Photo_Link__c = photourl;
                        newphoto.FixMyStreet__c = fix.Id;
                        //system.debug(newphoto);    
                        insert newphoto;
        	    	}
                }
                
             retid.add(fix.Id);
            }
            
            
        }

        
        
        
        List<FixMyStreet__c> retList = new List<FixMyStreet__c>();
      	retList =  database.query('SELECT '+fields+' FROM FixMyStreet__c where Id = :retid');
        result = JSON.serializePretty(retList);

   
		RestContext.response.addHeader('Content-Type', 'application/json');
		RestContext.response.responseBody = Blob.valueOf(result);
    } 
    
    /*
    //@HttpPost
    global static List<FixMyStreet__c> createFixMyStreetOLD()
    {
        String requestBody = RestContext.request.requestBody.toString();
        
        List<FixMyStreet__c> fixList = (List<FixMyStreet__c>) JSON.deserialize(requestBody, List<FixMyStreet__c>.class);
        
        List<FixMyStreet__c> retList = new List<FixMyStreet__c>();
        List<Id> retid = new List<Id>();
        
        for (FixMyStreet__c fix : fixList)
        {
        	if (fix.Id != null)
            {
                //do updated not insert
                string fixId = fix.Id;
             	FixMyStreet__c result =  database.query('SELECT status__c, Update_Comments__c FROM FixMyStreet__c where Id = :fixId');
                result.status__c = fix.status__c;
                result.Update_Comments__c = fix.Update_Comments__c;
                upsert result;
                // add new comment to related comments list
                FixMyStreet_Comments__c newcomment = new FixMyStreet_Comments__c(
                    	Comment__c = fix.Update_Comments__c, 
                    	Comment_Id__c = fix.Update_Comments_Id__c,
                    	Comment_Date__c = datetime.now(),
                    	FixMyStreet__c=fixId);
                insert newcomment;                
            }
            else                
            {
                // new record
            insert fix;
            }
            retid.add(fix.Id);
        }
        
    	//get object fields
        List<String> fieldList = new List<String>(Schema.getGlobalDescribe().get('FixMyStreet__c').getDescribe().fields.getMap().keySet());
        String fields = String.join(fieldList,',');       
       
    	retList =  database.query('SELECT '+fields+' FROM FixMyStreet__c where Id = :retid');
     
        return retList;
    }    
*/
    
}